### ISSUE TITLE
btrfs volume icon changed from something disk-looking to a folder in 2.4.0

### ISSUE THREAD

**Issue by AdamWill** [storaged-project/blivet-gui#398]
Sorry for this late report - I thought I'd filed it before, but can't find a trace anywhere, so I'm doing it now.

With blivet-gui 2.4.0 (it seems), the icon for btrfs volumes changed from something sort of disk-y:

![oldvolicon](https://github.com/storaged-project/blivet-gui/assets/916551/f47ac6e3-2e71-4e08-bac7-62fd61833c48)

to, well, the folder icon:

![newvolicon](https://github.com/storaged-project/blivet-gui/assets/916551/d7c79c44-273c-404d-8dae-89edbeca9eb8)

This seems like a bit of an odd icon choice. Was it intentional, or a mistake?

**Comment by vojtechtrefny** [comment]
That's intentional: https://github.com/storaged-project/blivet-gui/pull/360 I've been using the "drive-multidisk" icon for btrfs and LVM, but it the non-symbolic icon was removed and I think the symbolic one just doesn't look right. The folder icon is also bad but from my point of view less bad than the symbolic icon. I am definitely open to suggestion for a better icon or a better solution (but I'd like to avoid packaging my own icons).

Btw. this is how the multidisk icon looked originally: 
![image](https://github.com/storaged-project/blivet-gui/assets/5063197/a7eefbe2-7ebf-433e-8062-59efa2e990c7)

**Comment by AdamWill** [comment]
OK, I'll mark the openQA needle as just a normal needle not a workaround, then. thanks!

**Comment by vojtechtrefny** [comment]
Thanks. I'll try to remember to warn you next time I'll decide to change something.
