### ISSUE TITLE
blivet-gui already running after "Force Close" the application

### ISSUE THREAD

**Issue by bekicot** [storaged-project/blivet-gui#68]
Step to reporduce
1. open blivet-gui application
2. force stop it, my case was the app is not responsive and fedora offers me to force close it.

I think the problem rely on the `pid` package which is in https://github.com/rhinstaller/blivet-gui/blob/master/blivet-gui-daemon#L102 stated that when there is an error creating a new pid object, it declare the app as still running. I think it should also checking, wether the pid is still being used by blivet-gui, if it does, then it is running, and if it is not, then should remove it and retry the file creation.

The problem is fixed by
```
sudo rm /var/run/blivet-gui-daemon.pid 
```

**Comment by vojtechtrefny** [comment]
The `pid` module should check if the process is running when calling `create()`. But the problem is that blivet-gui actually has two processes -- one for the GUI (running as "normal" user) and one for the backend (running as root). If you force quit the GUI, the backend/daemon process is not killed. (And the pidfile contains pid of the daemon process.)

I'll check if the pidfile modules works as expected, but I'm quite sure this is not the problem. I'll also update the error message to make this more clear.

**Comment by bekicot** [comment]
@vojtechtrefny that may also be the case. Thanks for checking out.

**Comment by vojtechtrefny** [comment]
I've changed the error message in #97, it now also includes command to kill the backend/server process.
